require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

# Disabled on our repo's to enable polyglot-release
# TODO: Uncomment once rubocop > 1.40
#Gemspec/RequireMFA:
#  Enabled: false

# TODO: Re-enable cop (true), once rubocop-rspec > 2.11
#Metrics/BlockLength:
#  Enabled: false

Layout/LineLength:
  Max: 200

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

RSpec/MessageSpies:
  EnforcedStyle: receive
