require:
  - rubocop-performance
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

# Stylistic preference for cucumber
Gemspec/DevelopmentDependencies:
  Enabled: false

# Disabled on our repo's to enable polyglot-release
Gemspec/RequireMFA:
  Enabled: false

# This is a leftover issue due the name of the gem. Just ignore it in this one file.
Naming/FileName:
  Exclude:
    - lib/cucumber-compatibility-kit.rb

Style/Documentation:
  Enabled: false
