name: Release Python

on:
  push:
    branches: [release/*]

jobs:
  publish-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098 # v7.3.1
        with:
          enable-cache: true
          python-version: "3.14"
          version: "0.10.9"

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          package-manager-cache: false
      - name: Copy the samples to the package
        run: npm ci && npm run copy-to:python
        working-directory: devkit

      - name: Build package
        working-directory: python
        run: uv build

      - name: Publish package
        working-directory: python
        run: uv publish
