name: Release npm module

on:
  push:
    branches:
      - release/*

  pull_request:
    branches:
      - main

jobs:
  pre-release-check:
    steps:
      - run: echo "precheck"
    # uses: cucumber/.github/.github/workflows/prerelease-checks.yml@main

  publish-npm:
    name: Publish NPM module
    needs: [pre-release-check]
    runs-on: ubuntu-latest
#    environment: Release

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          cache-dependency-path: devkit/package-lock.json

      - name: Copy the samples to javascripts/features
        run: npm ci && npm run copy-to:javascript
        working-directory: devkit

      - uses: actions/setup-node@v3
        with:
          node-version: "17"
          cache: "npm"
          cache-dependency-path: javascript/package-lock.json

      - run: npm install-ci-test
        working-directory: javascript

      - run: ls -l javascript/features/**

      # - uses: cucumber/action-publish-npm@v1.1.0
      #   with:
      #     npm-token: ${{ secrets.NPM_TOKEN }}
      #     working-directory: javascript
