name: Release JavaScript

on:
  push:
    branches:
      - release/*

jobs:
  pre-release-check:
    uses: cucumber/.github/.github/workflows/prerelease-checks.yml@main

  publish-npm:
    name: Publish NPM module
    needs: [pre-release-check]
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          cache: "npm"
          cache-dependency-path: devkit/package-lock.json
      - name: Copy the samples to javascript/features
        run: npm ci && npm run copy-to:javascript
        working-directory: devkit
      - uses: actions/setup-node@v5
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: javascript/package-lock.json
      - run: npm install-ci-test
        working-directory: javascript
      - uses: cucumber/action-publish-npm@v1.1.1
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
          working-directory: javascript
