name: Release NPM

on:
  push:
    branches: [release/*]

permissions:
  id-token: write
  contents: read

jobs:
  publish-npm:
    name: Publish NPM module
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '24.x'
          cache: "npm"
          cache-dependency-path: devkit/package-lock.json
      - name: Copy the samples to javascript/features
        run: npm ci && npm run copy-to:javascript
        working-directory: devkit
      - uses: actions/setup-node@v5
        with:
          node-version: '24.x'
          cache: 'npm'
          cache-dependency-path: javascript/package-lock.json
          registry-url: 'https://registry.npmjs.org'
      - run: npm install-ci-test
        working-directory: javascript
      - run: npm publish
        working-directory: javascript
